var num1=100;
var num2=300;
var num3=600;
console.log("-----------Before Swap---------");
console.log(num1);
console.log(num2);
console.log(num3);
console.log("----------After Swap Value------");
var num4=num1;
num1=num2;
num2=num3;
num3=num4;
console.log(num1);
console.log(num2);
console.log(num3);